export const FETCH_ORDER_BY_HASH_SUCCESS = 'FETCH_ORDER_BY_HASH_SUCCESS'
export const FETCH_ORDER_BY_HASH_ERROR = 'FETCH_ORDER_BY_HASH_ERROR'

export const FETCH_LIQPAY_FORM_SUCCESS = 'FETCH_LIQPAY_FORM_SUCCESS'
export const FETCH_LIQPAY_FORM_ERROR = 'FETCH_LIQPAY_FORM_ERROR'
