export const PRODUCT_LIST_FETCH_PROCESSING = 'PRODUCT_LIST_FETCH_PROCESSING'
export const PRODUCT_LIST_FETCH_SUCCESS = 'PRODUCT_LIST_FETCH_SUCCESS'
export const PRODUCT_LIST_FETCH_ERROR = 'PRODUCT_LIST_FETCH_ERROR'

export const PRODUCT_ITEM_FETCH_PROCESSING = 'PRODUCT_ITEM_FETCH_PROCESSING'
export const PRODUCT_ITEM_FETCH_SUCCESS = 'PRODUCT_ITEM_FETCH_SUCCESS'
export const PRODUCT_ITEM_FETCH_ERROR = 'PRODUCT_ITEM_FETCH_ERROR'

export const FILTERS_LIST_FETCH_PROCESSING = 'FILTERS_LIST_FETCH_PROCESSING'
export const FILTERS_LIST_FETCH_SUCCESS = 'FILTERS_LIST_FETCH_SUCCESS'
export const FILTERS_LIST_FETCH_ERROR = 'FILTERS_LIST_FETCH_ERROR'

export const FILTER_LIST_SET_SUCCESS = 'FILTER_LIST_SET_SUCCESS'
export const LIMIT_SET_SUCCESS = 'LIMIT_SET_SUCCESS'
export const GRADE_SET_SUCCESS = 'GRADE_SET_SUCCESS'
export const CAT_ID_SET_SUCCESS = 'CAT_ID_SET_SUCCESS'

export const CART_FETCH_PROCESSING = 'CART_FETCH_PROCESSING'
export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS'
export const CART_FETCH_ERROR = 'CART_FETCH_ERROR'

export const MENU_FETCH_PROCESSING = 'MENU_FETCH_PROCESSING'
export const MENU_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS'
export const MENU_FETCH_ERROR = 'MENU_FETCH_ERROR'

export const BREADCRUMBS_SET = 'BREADCRUMBS_SET'
export const PRODUCT_ITEM_EMPTY = 'PRODUCT_ITEM_EMPTY'

export const SEND_REVIEW_PROCESSING = 'SEND_REVIEW_PROCESSING'
export const SEND_REVIEW_SUCCESS = 'SEND_REVIEW_SUCCESS'
export const SEND_REVIEW_ERROR = 'SEND_REVIEW_ERROR'

export const SET_PRICE_RANGE = 'SET_PRICE_RANGE'
