export const SET_CHECKOUT_INFO = 'SET_CHECKOUT_INFO'

export const FETCH_OF_NOVA_POSHTA_REGIONS_SUCCESS = 'FETCH_OF_NOVA_POSHTA_REGIONS_SUCCESS'
export const FETCH_OF_NOVA_POSHTA_REGIONS_ERROR = 'FETCH_OF_NOVA_POSHTA_REGIONS_ERROR'

export const FETCH_OF_NOVA_POSHTA_CITIES_SUCCESS = 'FETCH_OF_NOVA_POSHTA_CITIES_SUCCESS'
export const FETCH_OF_NOVA_POSHTA_CITIES_ERROR = 'FETCH_OF_NOVA_POSHTA_CITIES_ERROR'

export const FETCH_OF_NOVA_POSHTA_WAREHOUSES_SUCCESS = 'FETCH_OF_NOVA_POSHTA_WAREHOUSES_SUCCESS'
export const FETCH_OF_NOVA_POSHTA_WAREHOUSES_ERROR = 'FETCH_OF_NOVA_POSHTA_WAREHOUSES_ERROR'

export const SET_HASH_FOR_ORDER = 'SET_HASH_FOR_ORDER'
