export const FETCH_SEARCH_BY_STRING_SUCCESS = 'FETCH_SEARCH_BY_STRING_SUCCESS'
export const FETCH_SEARCH_BY_STRING_ERROR = 'FETCH_SEARCH_BY_STRING_ERROR'
export const LIMIT_SET_SUCCESS = 'LIMIT_SET_SUCCESS'
export const RESET_SEARCH = 'RESET_SEARCH'
